name: Node.js CI + Discord notification

on:
  pull_request:
    branches:
      - "master"
      - "issue-fix"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Run WebDriverIO Tests
      run: npx wdio run wdio.conf.js
    - run: npm run electron-build
    - name: Send Discord Notification
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          color=3066993
        else
          color=15158332
        fi
    
        curl -X POST -H "Content-Type: application/json" \
        -d "$(jq -n --arg status "${{ job.status }}" \
                     --arg branch "${{ github.ref_name }}" \
                     --arg repo "${{ github.repository }}" \
                     --arg event "${{ github.event_name }}" \
                     --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                     --argjson color "$color" \
        '{
          username: "GitHub Actions",
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
          embeds: [{
            title: "Build Notification",
            description: "The job has **\($status)** for branch `\($branch)`.",
            color: $color,
            fields: [
              {name: "Repository", value: $repo},
              {name: "Event", value: $event}
            ],
            timestamp: $timestamp
          }]
        }')" \
        https://discord.com/api/webhooks/1310623401638887526/sNNe8i_2j9pu3uG-7UNnPGshWRLkakupS4ENTFDMklyhAYzV6m_Ni6yi8o_ql2kvE5ya
    - name: Audit Dependencies
      run: npm audit --production

    
